### ISSUE TITLE
Update content with new changes to Master branch

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/node-manager-training#38]
changelog https://gitlab.oceantrack.org/otn-partner-nodes/ipython-utilities/-/blob/master/CHANGELOG.MD

**Comment by naomitress** [comment]
Notebook Changes: 

-     tag - 1b - Check duplicate.ipynb - added engine dispose to the end of the notebook. 
-     detections - 3 - detections_yyyy into otn_detections.ipynb - removed sync corrected times step from the notebook. Will be a step in the dbfixes scripts. 
-     Create and Update.ipynb - removed printSQL statement from the cpj.create_project_contact_new_db_struct function call. 
-     detections - 2b - timedrift calculations.ipynb - update_detection_time function now loops for each year specified.

**Comment by CaitlinBate** [comment]
- removed this section 
```
###  OPTIONAL: Syncing Corrected Times

The next two cells are used **only** if you have loaded detections through to the `otn_detections_yyyy` tables **without** first running the `detections - 2b - timedrift` calculations. You will need to provide the date of the current push and the link of the issue you are loading. You will then be able to correct the times and if  a node's detection times are updated the node's `obis.detection_extract` list will also be updated.
```

- edited the 2b description to remove mention that it needs to be run manually on each year, and noted that the notebook will identify the years required.

**Comment by CaitlinBate** [comment]
changed

```
First, you should run this cell with `printSQL = True`. If there are no errors, you can edit and change to `printSQL = False` and run again. This will add each contact to the database, into the `obis.contacts` and `obis.contacts_projects` tables.
```

to be 

```
The next cell writes to the database: **STOP** - confirm there is no Push currently ongoing. This cell will add each contact to the database, into the `obis.contacts` and `obis.contacts_projects` tables, as needed.
```

**Comment by CaitlinBate** [comment]
`tag - 1b - Check duplicate.ipynb - added engine dispose to the end of the notebook. ` --> this doesnt need to be noted

**Comment by CaitlinBate** [comment]
https://github.com/ocean-tracking-network/node-manager-training/commit/763241d440bc617c4bea0104c2df18607467c698
