### ISSUE TITLE
Update 05_project_metadata for researchers with own plone instance

### ISSUE THREAD

**Issue by bmanjones** [ocean-tracking-network/node-manager-training#41]
For researchers who are running their own plone instance, the line 444 in 05_project_metadata should be updated to state that they do not have to specify a node. Their repository will be set up in a way where their new project files will be entered into /data/repository/projectname folder instead of /data/repository/**node**/projectname.

similar, add the hint that the base_url in the plone auth json needs to end in a slash `/`

**Comment by CaitlinBate** [comment]
done and done

> To create the project folder you must first enter the relevant Node:
> - otnunit: `node = None`
> - safnode, migramar, nepunit:`node = "node"` - lowercase with quotation marks, fill in the value based on the path in Plone.
> - all other nodes (not hosted by OTN): `node = None`

---


> - This will bring you to a list of folders and notebooks. Select the `plonetools` folder. From there, select the `plone_auth.json` file and input your Plone base URL, username, and password. **Hint:** ensure the base_url in your json file ends in a slash, like `https://members.oceantrack.org/`!

**Comment by CaitlinBate** [comment]
https://github.com/ocean-tracking-network/node-manager-training/commit/763241d440bc617c4bea0104c2df18607467c698
