### ISSUE TITLE
fix NMT setup to match ipython

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/node-manager-training#45]
https://ocean-tracking-network.github.io/node-manager-training/setup.html is wrong

https://gitlab.oceantrack.org/otn-partner-nodes/ipython-utilities/-/wikis/New-Install-of-Ipython-Utilities is right

**Comment by jackVanish** [comment]
This seems to have been covered off by https://github.com/ocean-tracking-network/node-manager-training/pull/57 so I'm gonna close the ticket.
