### ISSUE TITLE
Add documentation for Movers curriculum

### ISSUE THREAD

**Issue by yingniu** [ocean-tracking-network/node-manager-training#50]
Create Movers curriculum:
https://app.asana.com/0/1204282866896764/1204282866909552/f

**Comment by jdpye** [comment]
I think #51 closes this one!

**Comment by jackVanish** [comment]
The linked Asana task is closed, the linked MR is merged, the lesson is present and accounted for, I do not think there's anything else to be done for this ticket, so I'm gonna close it; @yingniu if there's more to be done feel free to reopen this one.
