### ISSUE TITLE
Review Movers curriculum

### ISSUE THREAD

**Issue by yingniu** [ocean-tracking-network/node-manager-training#52]
- Branch is here: https://github.com/ocean-tracking-network/node-manager-training/edit/50_movers_curriculum/_episodes/20_movers_notebooks.md

- Poll request here: https://github.com/ocean-tracking-network/node-manager-training/pull/51
- Reviewers: @CaitlinBate @naomitress @SoftwareMonk 
1. please add use cases and keypoints.
2. Concerns: the page is very long, some content are the same as other data loading processes==> ying to add link to other pages.
3. Questions: should a) detailed explanations and b) example output sections to be added to this page? (edited)

**Comment by jdpye** [comment]
Caitlin and I reviewed and I merged but there are some steps to take still to integrate it into the lesson list. @jackVanish may be the one we need for that piece, but the review (and this ticket) is I believe complete.

**Comment by jackVanish** [comment]
Did a little bit of fussing to get the lesson showing up (fixed some syntax and tweaked some settings in the GitHub backend) but now the lesson is up and if Caitlin and Jon have reviewed and merged then everything should be A-OK here, so per Jon I'll close the ticket.
