### ISSUE TITLE
Add workflow description for adding new taxa to WoRMS

### ISSUE THREAD

**Issue by jdpye** [ocean-tracking-network/node-manager-training#54]
We mention WoRMS as our taxonomic reference database a few times but we don't outline the process of adding new vernaculars and new scientific names to WoRMS when they don't already have a listing for a species. This will be common in fresh water species, as they are not strictly tasked to be a taxonomic reference for freshwater.

As the Node Manager Training is a large part of our procedural documentation internally as well as an invaluable resource for our Nodes, we ought to define our process for adding new taxa. The process, informally, is to email info@marinespecies.org with a literature record that describes/defines the taxa we are looking to add. There are questions about freshwater species being out of scope for WoRMS (GBIF uses Catalogue of Life instead) but i think we offer that advice to node managers in the lesson when faced with taxa that aren't currently in WoRMS but they believe should be included.

**Comment by jackVanish** [comment]
PR merged, closing ticket.
