### ISSUE TITLE
vis lesson

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/node-manager-training#55]
https://ocean-tracking-network.github.io/node-manager-training/09_Supplementary%20notebooks/index.html

include:
- how to clone
- how to open notebooks
- brief intro about some of the cool notebooks, with screenshots of graphs

**Comment by jdpye** [comment]
draft of this was merged with https://github.com/ocean-tracking-network/node-manager-training/tree/2024_agenda_and_jon_edits and a fuller draft is still outstanding.  I'll make a fresh branch for that.
