### ISSUE TITLE
DB fix lesson review

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/node-manager-training#56]
https://github.com/ocean-tracking-network/node-manager-training/blob/database_fix_notebooks/_episodes/10_Database%20fix%20notebooks.md

**Comment by CaitlinBate** [comment]
These corrections can be done using the [Database fix notebooks](https://gitlab.oceantrack.org/otn-partner-nodes/database-fix-notebooks). These are the tools we can use to correct the identified errors, if the tool to do so already exists. ----> These corrections can be done using the [Database fix notebooks](https://gitlab.oceantrack.org/otn-partner-nodes/database-fix-notebooks). These are the tools we have built so far to correct commonly identified errors.

**Comment by CaitlinBate** [comment]
This suite of notebooks, however, should be used as a last option. If an error comes up from the verification notebooks, human eyes and critical thinking should be used to check if the database fix notebooks should be used and, depending on the type of fix, researcher permission may need to be obtained. ----> This suite of notebooks, however, should only be used as a **last option**. If an error is identified by verification checks, human eyes and critical thinking must be used to check if the database fix notebooks are required and, depending on the type of fix, researcher permission often needs to be obtained.

**Comment by CaitlinBate** [comment]
>Create and activate the "nodebook" python enviornment. The creation process will only need to happen once.
In your terminal, run the command conda create -n nodebook python=3.9
Activate the nodebook environment using conda activate nodebook

are we naming this environment the same as our ipython env? should it be a new env?

**Comment by CaitlinBate** [comment]
the heading "Gitlab Kdbx integration" should have different caps like "Gitlab KDBX Integration"

**Comment by CaitlinBate** [comment]
>One interesting part of the Database Fix Notebooks is that if you add a Gitlab token to your kdbx file, it will automatically add the results from the notebook to the created Gitlab issue. Otherwise, you will have to copy and paste the displayed results manualyl into the comments (as directed by the notebook). ---> An exciting feature of the Database Fix Notebooks is that if you add a Gitlab token to your kdbx file, the notebook will automatically comment the output from the notebook directly into the specified DB-fix Gitlab issue.

**Comment by CaitlinBate** [comment]
>The first step when a researcher tell you about an incorrect database value is to create a new Gitlab Issue with the DB Fix Issue checklist template. ----> The first step when you have confirmed an incorrect database value is to create a new Gitlab Issue with the DB Fix Issue checklist template.

**Comment by CaitlinBate** [comment]
>There are a few helpful explanation notebooks inside this suite of notebook. ---> There are a few helpful explanation notebooks inside this suite Database Fix tools. You should always start by accessing both of these in order to identify next steps.

**Comment by CaitlinBate** [comment]
Some of the database fix notebooks require a spreadsheet of the changes. These will be evident by the notebook top description or the description on 0. Home.ipynb.

The required columns will be shown in the description. If there are missing required columns, the notebook will display an error with which columns are missing.

---->

Some of the Database Fix Notebooks require the user provides a spreadsheet of the changes as input. This requirement will be specified in the top description in each Notebook, or the description on 0. Home.ipynb.

The required columns will be shown in the description as well. Once input, if there are missing required columns, the notebook will display an error identifying which columns are missing.

**Comment by CaitlinBate** [comment]
general comment: we should be consistent with the text and always put "Database Fix Notebook". some lines have no capitalization, some lines say DB fix notebook etc

**Comment by CaitlinBate** [comment]
> The first step is to create a Gitlab issue with the relevant information titled 'CODE Change receiver serial'.

can we put a screenshot of the gitlab issue in here? so people remember its the first step haha

**Comment by CaitlinBate** [comment]
>After pressing 'Next' after filling in the relevant information, the backend code will perform verifications on the changes to make sure, e.g. that no resulting overlapping receivers occur after the change. If this is the case, the change will not occur and an error message will be displayed showing why the change was not made. ---> Once you press 'Next' after filling in the relevant information, the backend code will perform verifications on the changes to make sure, e.g. that no resulting overlapping receivers occur after the change. If this is the case, the change will not occur and an error message will be displayed showing why the change was not made.

in all examples

**Comment by CaitlinBate** [comment]
> IMPORTANT Please double check the update steps to ensure the notebook is performing accurately. ---> :star: **IMPORTANT** :star: Please double check the update steps to ensure the notebook is performing accurately.

in all examples

**Comment by CaitlinBate** [comment]
>If you have a gitlab token authorization associated with your kdbx, as mentioned above, the notebook will automatically add the updates and success message in a comment to the created Gitlab ticket. Otherwise, it will tell you to copy and paste the update list and success message. ---> If you have a gitlab token authorization associated with your kdbx, as mentioned above, the notebook will automatically comment the updates and success message in the specified Gitlab ticket. Otherwise, it will tell you to copy and paste the update list and success message.

in all examples

**Comment by CaitlinBate** [comment]
>The logic of both options will work the same but differ in the way to select the download(s) to delete. For the selectable table, you can click or Control-click on the rows on the actual table. For the drop-down, you can click or Control-clik on the catalognumber(s) in the drop-down. IMPORTANT Make sure the catalognumber(s) in the drop-down you select matches the catalognumber(s) in the table. ---> The logic of both options will work the same but differ in the way to select the download(s) to delete. For the selectable table, you can click or Control-click on the rows on the actual table. For the drop-down, you can click or Control-clik on the catalognumber(s) in the drop-down. 

>IMPORTANT Make sure the catalognumber(s) in the drop-down you select matches the catalognumber(s) in the table.

adding a space here

**Comment by CaitlinBate** [comment]
>For each duplicate download group, you can check which download(s) are incorrect and should be deleted. You can do this using the guidance in the instructions in the notebook. If the downloads are matched to different receivers, the correct download matching is the one with the closest download date to its receiver's end date and the other rows should be deleted. If they are matched to the same receiver, the correct download is the one with the most accurate catalognumber. This could be of the format {receiver_catalognumber}-{download_date}. The other rows should be deleted. In the table, there is a '***' in the 'recommended' column which shows which rows the notebook recommends to delete but sometimes it can be inaccurate so we recommend human eyes on it to double check that it is the one(s) you intend to delete. --->

For each duplicate download group, you can check which download(s) are incorrect and should be deleted. You can do this using the guidance in the instructions in the notebook. 
- If the downloads are matched to different receiver deployments, the correct download is the one with the closest download date to its receiver's end date and the other rows should be deleted. 
- If they are matched to the same receiver deployment, the correct download is the one with the most accurate catalognumber. This could be of the format {receiver_catalognumber}-{download_date}. The other rows should be deleted. 

In the displayed table, there is a '***' in the 'recommended' column which shows which rows the notebook recommends to delete but sometimes it can be inaccurate so we require human eyes on it to double check that it is the one(s) you intend to delete.

**Comment by CaitlinBate** [comment]
>The first row should be deleted since the downloads are matched to the same receiver but the download catalognumber is not in the expected format {receiver_catalognumber}-{download_date}. ---> The first row should be deleted since the downloads are matched to the same receiver deployment but the download catalognumber is not in the expected format {receiver_catalognumber}-{download_date}.

**Comment by diniangela** [comment]
Thank you for reviewing! Made the changes in the document
