### ISSUE TITLE
2024 Training Cleanup - Project Metadata

### ISSUE THREAD

**Issue by jackVanish** [ocean-tracking-network/node-manager-training#58]
Forked from https://github.com/ocean-tracking-network/node-manager-training/issues/49 to track the changes specifically to project metadata.

- [x] Checklist at the start of the lesson needs to be updated. 
- [x] Under the "Project Metadata Parser" section, the input options need more clarity regarding their being two different cells, only one of which needs to be run. 
- [x] Under "Manual Fields", the definition of shortname needs to be amended.
- [x] There is a typo in 'Skip to Verification': "You should enter run these cells..." should not have "enter"
- [x] "Passed off to an OTN analyst" in the Final Steps section should have language for those who do not rely on OTN for verification.

**Comment by jackVanish** [comment]
Checked off entries are covered in https://github.com/ocean-tracking-network/node-manager-training/pull/70 . Leaving the last one to be done when the content folk have signed off on alternative language to use in that section.

**Comment by slandovs** [comment]
We are leaving "Passed off to an OTN analyst" because even thought RAFT is currently not passing to us, they should be. Which means the language in this step should still be accurate for all nodes

**Comment by slandovs** [comment]
- [ ] the hyperlink to the template (https://members.oceantrack.org/data/data-collection) in the 'create and update projects' notebook is broken @jackVanish 

reviewed the .md file and made minor edits (replaced the word 'info' with information, corrected some spelling mistakes, etc). Going to review my other lesson and then will make a PR

**Comment by CaitlinBate** [comment]
conceptual things we decided in the meeting today https://github.com/ocean-tracking-network/node-manager-training/pull/70#discussion_r1848508073

**Comment by jackVanish** [comment]
Assuming that the language regarding OTN Analysts is also not changing here (following Shannon's comment in issue 60). 

Once the associated merge request is handled (#70 ), we're good to go.

**Comment by jackVanish** [comment]
Merge complete, closing ticket.
