### ISSUE TITLE
2024 Training Cleanup - Tag Metadata

### ISSUE THREAD

**Issue by jackVanish** [ocean-tracking-network/node-manager-training#59]
Forked from https://github.com/ocean-tracking-network/node-manager-training/issues/49 to track changes to the Tag Metadata section. 

- [x] Checklist at the top needs to be updated. 
- [ ] "Verification of File Contents" section needs to be reviewed for accuracy
- [ ] "Verifying Cache"/"Verifying OTN Tables" need to be checked for completeness. 
- [x] Decision needs to be made as to whether "floy" will be swapped out in favour of a more generic term. 
- [x] Typo in "Verification of File Contents - formatting": in the second sentence "Generally, it will be names ...." should be "named"
- [x] "Checking for Duplicates" section requires clearer language around "moving on" when no duplicates are found. 
- [x] Instructions in "Verification of OTN tables" should direct users to the DB fix modules rather than instructing them to fix the database entries manually. 
- [x] Final Steps section requires additional clarity for users who do not rely on OTN staff for final verification.

**Comment by CaitlinBate** [comment]
first PR created, more to come

**Comment by jackVanish** [comment]
First PR merged.

**Comment by jackVanish** [comment]
The amend to instructions in Verification of OTN tables seems to be done so I ticked the box.

**Comment by jackVanish** [comment]
@jdpye and I chatted and apparently a dual content review from us will cover off the second and third line items. For my part, nothing leapt out at me in either section as being missing or transparently wrong. When Jon has filed his brief, we'll be able to close this ticket.

**Comment by jdpye** [comment]
My review and Bruce's review have now been merged.
