### ISSUE TITLE
2024 Training Cleanup - Deployment Metadata

### ISSUE THREAD

**Issue by jackVanish** [ocean-tracking-network/node-manager-training#60]
Forked from https://github.com/ocean-tracking-network/node-manager-training/issues/49 to track changes to the Deployment Metadata lesson. 

- [x] Checklist at the top needs updating
- [x] "Verification of File Contents" section needs to be reviewed for accuracy
- [x] "Loading the Raw Table" section needs more clarity on "check that station locations have not changed stations "NAMES""
- [x] Typo in "Load events file into c_events_yyyy table": "Upon successful loading and can dispose of the engine..." but should say "Upon successful loading, you can dispose..." (or similar)
- [x] Final Steps section requires additional clarity for users who do not rely on OTN staff for final verification.
- [x] Verify Stations section requires additional clarity for users who do not rely on OTN staff to fix station record problems.

**Comment by slandovs** [comment]
i added more details on the station names check under the visual inspection section (this is where it actually happens) and then added in a Task List Checkpoint under it!

**Comment by slandovs** [comment]
for the typo in load events - I believe this should be in the detection loading ticket! @jackVanish

**Comment by slandovs** [comment]
all nodes should be getting OTN staff to do the final verification

**Comment by slandovs** [comment]
added some additional text about db fix notebooks for the verify stations section "If there are any errors, go into database and fix the `raw` table directly, or contact the researcher and then fix the `raw` table. If there are problems with records that have already been promoted to the `stations` or `moorings` tables, you will need to create a db fix ticket in Gitlab in order to correct the records in the database."

**Comment by slandovs** [comment]
reviewed the .md file and made some edits (updated sections to tell NMs to create db fix tickets, made some of the changes in the checklist in this issue, corrected some spelling mistakes, etc). Going to make a PR @jackVanish

**Comment by jackVanish** [comment]
> all nodes should be getting OTN staff to do the final verification

Should we take this to mean that the last remaining line item doesn't actually need to be done? If so we can close this ticket.

**Comment by jackVanish** [comment]
Got confirmation from Jon that this is OK to shut down.
