### ISSUE TITLE
2024 Training Cleanup - Detection Loading

### ISSUE THREAD

**Issue by jackVanish** [ocean-tracking-network/node-manager-training#61]
Forked from https://github.com/ocean-tracking-network/node-manager-training/issues/49 to track changes to Detection Loading lesson. 

- [x] Checklist at the top needs to be updated. 
- [x] "Convert to CSV" section needs more detail
- [x] Sections for dets-3b and -3c need more clarity for next steps after "track this information in a GitLab ticket." 
- [x] events-4 portion is incomplete and needs to be updated to match current functionality. 
- [x] Load Sentinel Detections section requires additional clarity. 
- [x] Final Steps section requires additional clarity for users who do not rely on OTN staff for final verification.

CB todo
- [x] - in PUSH lesson, check detection extract creation lesson is good
- [x] add "switch back to master" info

**Comment by CaitlinBate** [comment]
PR crreated for this

**Comment by jackVanish** [comment]
PR merged, closing this
