### ISSUE TITLE
2024 Training Cleanup - Supplementary Notebooks

### ISSUE THREAD

**Issue by jackVanish** [ocean-tracking-network/node-manager-training#63]
Forked from https://github.com/ocean-tracking-network/node-manager-training/issues/49 to track changes to the supplementary notebooks lesson. 

- [x] Link to the "convert - fathom" notebook in the detections module.
- [x] Check whether 'Active Tracking' is still an option after the updates to the movers notebooks and remove the relevant section if not. 
- [x] Slocum Telemetry and Telemetry Processing for Wave Gliders and Animals can be removed in favour of the Movers module. 
- [x] Receiver Operator Notebook section either needs to be removed, or reflect that it has a new name and is for internal use only.
- [x] DB-Fix notebooks section can be removed in favour of new module.
- [x] Push schedule needs to be updated (and decision needs to be made if specific dates should be included or if generic "third thursday of February/June/October" will be used).

**Comment by jackVanish** [comment]
@CaitlinBate @diniangela  Can you speak to items two, four, and six on this list? If so I can probably make a merge to knock this one off pretty quickly.

**Comment by CaitlinBate** [comment]
number 2: yes, Active tracking is still used (for now) for VR100 files

number 4: @jdpye should have more info about how we want to present the viz notebooks

number 6: I think generic is best, saves updating.

**Comment by diniangela** [comment]
For number 6: I updated the push schedule for 2024-2025 in the `process-flows` branch (https://github.com/ocean-tracking-network/node-manager-training/tree/process_flows), but agreed generic is best but that can include the future dates coming up

**Comment by jackVanish** [comment]
Ticked some boxes associated with https://github.com/ocean-tracking-network/node-manager-training/issues/64, which addresses everything except the vis question, for which I'll wait for JOn's input.

**Comment by jdpye** [comment]
Moved the coverage of the Receiver Operator Notebook to the Vis lesson in my branch (PR #62). We'll talk about internal-use versus publicly available data there.
