### ISSUE TITLE
2024 Training Cleanup - "Notebook" or "Nodebook"

### ISSUE THREAD

**Issue by jackVanish** [ocean-tracking-network/node-manager-training#67]
Lessons inconsistently switch between "Notebook" and "Nodebook", we should pick one and stick to it. I am in favour of 'notebook' and will make the requisite changes either way, and am soliciting opinions from @CaitlinBate and @slandovs (and others as well).

**Comment by CaitlinBate** [comment]
i like OTN Nodebooks (caps) when talking about our tools, but its still running "jupyter notebooks" so need to ensure we don't find-and-replace them all

**Comment by jackVanish** [comment]
https://github.com/ocean-tracking-network/node-manager-training/pull/71 I have a Merge request open that will hopefully address this @CaitlinBate

**Comment by jackVanish** [comment]
Caitlin approved the merge so I merged it, closing the ticket.
