### ISSUE TITLE
2024 Training Cleanup - Data Loading Workflow

### ISSUE THREAD

**Issue by jackVanish** [ocean-tracking-network/node-manager-training#68]
Forked from https://github.com/ocean-tracking-network/node-manager-training/issues/49 to track changes to the Data Loading Workflow lesson. 

- [x] Move the AUTH - Create and Update section into its own lesson. 
- [x] Include more information about GitLab access tokens.

**Comment by CaitlinBate** [comment]
PR created

**Comment by jackVanish** [comment]
PR Merged, closing the ticket.
