### ISSUE TITLE
BJ ToDos

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/node-manager-training#7]
- [x] node training database
- [x] auth files for all attendees
- [x] example data for all attendees (tags, dets, deploy)
- [x] edit/review content in ep04 to ensure it aligns with the Node Training DB connection info

**Comment by CaitlinBate** [comment]
working on confirming attendees, emailed a couple people today to see if they are data learners or not.

current list:

Brian | Stirling | brian.stirling@csulb.edu
Cesar | Penaherrera | cesar.penaherrera@migramar.org
Claudia | Meneses | claudia.meneses@vliz.be --> **waiting for email confirmation**
Danielle | Morley | danimorley@gmail.com
Danny | O'Donnell | drodonnell@ucdavis.edu
Darnell | Gadberry | darnell.gadberry@csulb.edu --> **waiting for email confirmation**
Erin | Tracy | eetracy@ucdavis.edu
Fabrice | Jaine | fabrice.jaine@sims.org.au --> **waiting for email confirmation**
Frida | Lara Lizardi | fridalara131289@gmail.com
Godfrey | Padare | g.padare@saiab.nrf.ac.za
Joy | Young | joy.young@thefactnetwork.org
Kim | Richie | richiek@si.edu
Megan | McKinzie | mmckinzie@mbari.org
Scott | Colborne | scolbor@gmail.com
Taryn | Murray | TS.Murray@saiab.nrf.ac.za
Thomas | TinHan | ttinhan@hawaii.edu

**Comment by CaitlinBate** [comment]
New Data Learner:

Shannon Landovskis - [sh836795@dal.ca](mailto:sh836795@dal.ca)

**Comment by naomitress** [comment]
example data https://members.oceantrack.org/data/repository/fntp/nmt-files/
