### ISSUE TITLE
CB review

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/node-manager-training#94]
- [x] 1. setup.md: image isnt renderng (OTN Nodebooks - home page)\
- [x] 2. setup.md: remove section about Node Training Datasets! or point it here http://129.173.48.161/data/repository/node_training/node-training-files-1
- [x] 3. Into lesson: there is a PPT in there, it does NOT look like its up to date
- [x] 4. setup lesson: remove section about Node Training Datasets! or point it here http://129.173.48.161/data/repository/node_training/node-training-files-1 
- [x] 5. workflow lesson: "connecting to ur DB" -- need to update the DB name, IP etc
- [x] 6. tagging lesson: two typos here "Please ensure each tag aplpied to an animal (of any type) has its own row radio tags (inlcuing PIT, VHF), satellite tags (and more) each need their own row in the metadata sheet."
- [ ] 7. ~~detection: is there a "checking file format" or "table format" or something step in here now? double check notebooks. i know there is one for the vdat notebook~~ ----> I think this might be in tagging? checking if project si still active? idk
- [x] 8. detections" convert fathom instructions are wrong 
- [x] 9.  detections: after loading to dets_YYYY the tasklist checkpoint shouldn't be an "example" pop out. same issue MANY of the checkpoints??
- [x] 10. detections: also many of these checkpoints are wrong now and don't match the checklist at the top
- [x] 11. movers: load telemetry data has a link that doesn't work - delete
- [x] 12. movers: events 4 steps are wrong
- [x] 13. movers; troubleshoot tips has bad link
- [x] 14. db fix lesson: setup has a typo "cd /paht/to/database-fix-notebooks"
- [x] 15. db fix lesson: setup links to ipython install wiki which is wrong
- [x] 16.  db fix lesson; need more lines between examples, they are squished together
- [x] 17. push lesson: push report link should say 2024
- [x] 18. push lesson: do we need to be on integration or master for detection extracts? i thought master
- [x] 19. new features lesson: link to gitlab not a real link

**Comment by CaitlinBate** [comment]
@jdpye number 3 is relevant for yu - do you have a new PPT you can share that I can link there?

**Comment by jdpye** [comment]
Going to adapt and extend this slideshow, we can link it but can't download and include PPT

https://docs.google.com/presentation/d/1ZK58KCS_Zz8qHz5IYrBGYILJ-ZQYfkeo/edit?usp=sharing&ouid=108426455008350886281&rtpof=true&sd=true
